name: Go and Node.js Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Go check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go get dependencies
        run: go get -v -t -d ./...

      - name: Go format
        run: diff -u <(echo -n) <(gofmt -d .)

      - name: Go build
        run: make

      - name: Install protoc
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
          unzip protoc-3.11.4-linux-x86_64.zip bin/protoc

      - name: Go test protoc
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make test-protoc PROTOC=bin/protoc

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Node.js install dependencies
        working-directory: ./soltest
        run: npm ci

      - name: Node.js build
        working-directory: ./soltest
        run: npm run build --if-present

      - name: Node.js test
        working-directory: ./soltest
        run: npm test
